apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../../base/my-website

images:
- name: my-website
  newName: public.ecr.aws/r8m4q7l9/my-website
  newTag: ed6140ec03574b0eae20df1e3c363caebd8841dd

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: my-website
