apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../../base/my-website

images:
- name: my-website
  newName: public.ecr.aws/r8m4q7l9/my-website
  newTag: f76f015a337ca0d58e497284816589cbc85d0599

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: bug-website.com
  target:
    kind: Ingress
    name: my-website
