apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../base/my-website
images:
  - name: my-website
    newName: public.ecr.aws/r8m4q7l9/my-website
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: my-website
      