apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-website
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: myapp.example.com       # Domain ที่ต้องการ
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-website
                port:
                  number: 80
                  