apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../../base/meme-website

images:
- name: meme-website
  newName: public.ecr.aws/r8m4q7l9/meme-website
  newTag: 6d65c6e895831686f10befc560c73b1832edd60e

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: main-meme.bug-website.com
  target:
    kind: Ingress
    name: meme-website
